### ISSUE TITLE
Failed to create webhook configuration with v0.2.7 

### ISSUE THREAD

**Issue by binoue** [kubernetes-sigs/controller-tools#417]
**What happened**:

I updated controller-tools from v0.2.5 to v0.2.7 and generated our manifests from the source code scaffolded by `kubebuilder`.
The generated webhook manifests were like below and not properly generated.

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig: {}
  name: ""
...
```
After adding `matchPolicy="Equivalent"` marker, the manifest was properly generated.
Based on [this code](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L63), specifying `matchpolicy` is optional and this behavior looks like a bug. 

**What you expected to happen**:

I expected the generated manifests are the same as that by controller-tools v0.2.5

**Solution**:
Add the codes like below to handle the case where `matchpolicy` marker is not set.

```diff
--- a/pkg/webhook/parser.go
+++ b/pkg/webhook/parser.go
@@ -194,6 +194,8 @@ func (c Config) matchPolicy() (*admissionreg.MatchPolicyType, error) {
                matchPolicy = admissionreg.Exact
        case strings.ToLower(string(admissionreg.Equivalent)):
                matchPolicy = admissionreg.Equivalent
+       case "":
+               return nil, nil
        default:
                return nil, fmt.Errorf("unknown value %q for matchPolicy", c.MatchPolicy)
```

**Comment by djzager** [comment]
Looks like this was introduced in https://github.com/kubernetes-sigs/controller-tools/pull/408 and there was a follow-up in https://github.com/kubernetes-sigs/controller-tools/pull/411
but I don't see that in the release notes for [v0.2.7](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.2.7). 

@vincepri am I right in thinking this will be fixed in the next release of controller-tools?

**Comment by djzager** [comment]
Except this comment in the release notes leaves me confused.

> NB: this is virtually identical to the unpulished v0.2.6, except that we fixed an accidental breaking change in #408.

**Comment by vincepri** [comment]
v0.2.7 has https://github.com/kubernetes-sigs/controller-tools/commit/1c6d3844762fed588be5123e5b38ccbeb25d94e1 so it should be fixed

**Comment by vincepri** [comment]
`matchPolicy=Equivalent` should be valid

**Comment by jiachengxu** [comment]
but the `matchPolicy` is optional, so it also should work without setting the `matchPolicy`, but it is still not properly generated.

**Comment by vincepri** [comment]
@jiachengxu you're right, can you open a PR with your patch and we can get another release out?

@DirectXMan12 we should probably spend some time to add some test data for webhooks as well

**Comment by djzager** [comment]
/assign

Only because I already have the PR ready to submit.
